DROP TABLE STR_IN_ARRIVO;
DROP TABLE MAGAZZINO;
DROP TABLE LISTA_ORDINE;
DROP TABLE ORDINE;
DROP TABLE REGISTRO;
DROP TABLE DIPENDENTE_NEGOZIO;
DROP TABLE FORNITORE;
DROP TABLE ACQUISTA;
DROP TABLE PROMOZIONE;
DROP TABLE PRENOTAZIONE;
DROP TABLE CLIENTE;
DROP TABLE STRUMENTO;


CREATE TABLE STRUMENTO(
N_SERIE 	VARCHAR(10) PRIMARY KEY,
MODELLO 	VARCHAR(20),
MARCA 		VARCHAR(20),
TIPO		VARCHAR(20),
CATEGORIA	VARCHAR(20) NOT NULL,
PREZZO		NUMBER NOT NULL);


CREATE TABLE CLIENTE(
SSN			VARCHAR(16) PRIMARY KEY,
C_NOME		VARCHAR(16) NOT NULL,
C_COGNOME	VARCHAR(16) NOT NULL,
INDIRIZZO	VARCHAR(30),
C_TIPO		VARCHAR(20) CHECK(C_TIPO='Privato' or C_TIPO='Pubblico') NOT NULL);


CREATE TABLE ACQUISTA(
SSN			VARCHAR(16) NOT NULL,
N_SERIE		VARCHAR(10) UNIQUE NOT NULL,
PREZZO		NUMBER NOT NULL,
DATA_ACQUISTO DATE NOT NULL,
CONSTRAINT FK_SSN FOREIGN KEY (SSN) REFERENCES CLIENTE(SSN),
CONSTRAINT FK_N_SERIE1 FOREIGN KEY (N_SERIE) REFERENCES STRUMENTO(N_SERIE));


CREATE TABLE PRENOTAZIONE(
ID_PRENOTAZIONE	VARCHAR(16) PRIMARY KEY,
N_SERIE 		VARCHAR(10) NOT NULL,
SSN   			VARCHAR(16) NOT NULL,
DATA_PRENOTAZIONE	DATE NOT NULL,
CONSTRAINT FK_N_SERIE2 FOREIGN KEY (N_SERIE) REFERENCES STRUMENTO(N_SERIE),
CONSTRAINT FK_SSN2 FOREIGN KEY (SSN) REFERENCES CLIENTE(SSN));

CREATE TABLE PROMOZIONE(
ID_PROMO	 	VARCHAR(16) PRIMARY KEY,
N_SERIE 		VARCHAR(10) NOT NULL,
SCONTO			NUMBER NOT NULL,
DATA_INIZIO 	DATE NOT NULL,
DATA_FINE		DATE NOT NULL,
CONSTRAINT FK_N_SERIE3 FOREIGN KEY (N_SERIE) REFERENCES STRUMENTO(N_SERIE));


CREATE TABLE FORNITORE(
ID_FORNITORE	VARCHAR(16) PRIMARY KEY,
F_NOME			VARCHAR(16) NOT NULL,
INDIRIZZO 		VARCHAR(30),
N_TELEFONO 		VARCHAR(10));


CREATE TABLE DIPENDENTE_NEGOZIO(
CF					VARCHAR(16) PRIMARY KEY,
D_NOME				VARCHAR(16) NOT NULL,
D_COGNOME 			VARCHAR(16) NOT NULL,
DATA_N 				DATE,
SALARIO				NUMBER NOT NULL,
N_GIORNI_LAVORATIVI	NUMBER CHECK(N_GIORNI_LAVORATIVI>=0 AND N_GIORNI_LAVORATIVI<=28),
DISCRIMINATORE  	VARCHAR(20) CHECK(DISCRIMINATORE='RESPON_FORN' OR DISCRIMINATORE='DIPENDENTE' OR DISCRIMINATORE='CAPO_NEGOZIO') NOT NULL);


CREATE TABLE REGISTRO(
CF				VARCHAR(16) NOT NULL,
DATA_PRESENZA 	DATE NOT NULL,
ORE_LAVORO		NUMBER CHECK(ORE_LAVORO>=1 AND ORE_LAVORO<=12) NOT NULL,
CONSTRAINT FK_CF FOREIGN KEY (CF) REFERENCES DIPENDENTE_NEGOZIO(CF));


CREATE TABLE ORDINE(
ID_ORDINE		VARCHAR(16) PRIMARY KEY,
ID_FORNITORE	VARCHAR(16) NOT NULL,
RESPONSABILE  	VARCHAR(16) NOT NULL,
DATA_ACQUISTO 	DATE  NOT NULL,
DATA_ARRIVO		DATE  NOT NULL,
CONSTRAINT FK_ID_FORN FOREIGN KEY (ID_FORNITORE) REFERENCES FORNITORE(ID_FORNITORE),
CONSTRAINT FK_CF1 FOREIGN KEY (RESPONSABILE) REFERENCES DIPENDENTE_NEGOZIO(CF));


CREATE TABLE LISTA_ORDINE(
ID_ORDINE 	VARCHAR(16) NOT NULL,
N_SERIE 	VARCHAR(10) UNIQUE NOT NULL,
PREZZO		NUMBER NOT NULL,
CONSTRAINT FK_ID_ORD FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID_ORDINE),
CONSTRAINT FK_N_SERIE4 FOREIGN KEY (N_SERIE) REFERENCES STRUMENTO(N_SERIE));


CREATE TABLE MAGAZZINO(
N_SERIE VARCHAR(10) UNIQUE NOT NULL,
PREZZO	NUMBER NOT NULL,
CONSTRAINT FK_N_SERIE5 FOREIGN KEY (N_SERIE) REFERENCES STRUMENTO(N_SERIE));

CREATE TABLE STR_IN_ARRIVO(
N_SERIE VARCHAR(10) UNIQUE NOT NULL,
PREZZO NUMBER NOT NULL,
DATA_ARRIVO DATE NOT NULL,
CONSTRAINT FK_N_SERIE7 FOREIGN KEY (N_SERIE) REFERENCES STRUMENTO(N_SERIE));






































